function [genA , V, D] = generators( n )
% This function should help me organise myself for different input
% matrices. 


    
if n == 1.1                         % First Wu2007 example, part 1. The Js are not included because Wu is not symplectic. This follows Wu's bounds. We see that we maybe get LARC but maybe not cont...if the manifold is dim=2. %%%%%%%%%%%%%%%%%%%%%%
    KX = 0.5*[0 -1i; 1i 0];
    KY = 0.5*[0 -1; -1 0];
    KZ = 0.5*[-1i 0; 0 1i];

    e = 1; a = 0.5;
    
    genA{1} = e*KX+a*KZ;
    genA{2} = KY;
    
    V = 0; D = 0;
    
elseif n == 1.2                     % First Wu2007 example,  part 2. The Js are not included because Wu is not symplectic. In this case it looks like we may satisfy Huang but not LARC...this would be bad. So what is the dimension of the manifold?  %%%%%%%%%%%%%%%%%%%%%
    KX = 0.5*[0 -1i; 1i 0];
    KY = 0.5*[0 -1; -1 0];
    KZ = 0.5*[-1i 0; 0 1i];

    e = 1; a = 1;
    
    genA{1} = e*KX+a*KZ;
    genA{2} = KY;
    
    V = 0; D = 0;
    
elseif n == 2                       % First Wu2007 example. The Js are not included because Wu is not symplectic.
    KX = 0.5*[0 -1i; 1i 0];
    KY = 0.5*[0 -1; -1 0];
    KZ = 0.5*[-1i 0; 0 1i];
    omega0 = 3;

    genA{1} = omega0*KZ;
    genA{2} = KX;
    
    V = 0; D = 0;
elseif n == 3                       % SU(2) example.
    genA{1} = [0 1i; 1i 0];
    genA{2} = [0 -1; 1 0];
    
    V = 0; D = 0;
    
elseif n == 4                       % Trivial example where we get out B as an ideal and C does not have full rank.
    genA{1} = [1 2 ; 3 4];
    genA{2} = [1 0 ; 0 1];
    genA{3} = -[1 0 ; 0 1];
    
    V = 0; D = 0;
    
elseif n == 5                       % Genoni2012 example. %%% We get that sp(6,R) is not generated by this hamset. This is worrying as Genoni claims that LARC is satisfied. This is a commutator problem. %%%%%%%%%%%%
    a = 2; b = 3; c = 4; d = 5;     % a = omega, b = g, omega_1 = c, chi = d.
    H1 = [a 2*b 0 0 0 0 ; 2*b a 2*b 0 0 0 ; 0 2*b a 0 0 0 ; 0 0 0 a 0 0 ; 0 0 0 0 a 0 ; 0 0 0 0 0 a];
    h2 = [c 0 0 c 0 0];
    H2 = diag(h2);
    h3 = [2*d 0 0 -2*d 0 0];
    H3 = diag(h3);
    
    k = 3;
    J = [zeros(k) eye(k) ; -eye(k) zeros(k)];
    
    genA{1} = J*H1;
    genA{2} = J*H2;
    genA{3} = J*H3;
    
    [V,D] = eig(genA{1});
    
elseif n == 6                       % (Beginning of hammat set) Matrices got from the wiki. Here we have that DI implies B = C. However genA{1} is diagonal so of course...I don't think it is Hamiltonian.
    genA{1} = 1i*[1 0 ; 0 1];
    genA{2} = [0 0; 1 0];
    genA{3} = [0 1; 0 0];
    
    [V,D] = eig(genA{1});
    
elseif n == 7                       % Variation on above where I actually make it Hamiltonian.
    genA{1} = 1i*[1 0 ; 0 -1];
    genA{2} = [0 0; 1 0];
    genA{3} = [0 1; 0 0];
    
    [V,D] = eig(genA{1});
    
elseif n == 8                       % Provides an example of a DI drift generator that gives B=C. The set generates sp(4).
    h1 = [2 -2 3 -3];
    H1 = diag(h1);
    H2 = [1 2 0 0; 2 1 0 0; 0 0 1 0; 0 0 0 1];
    H3 = [2 3 4 0; 3 2 0 0; 4 0 2 0; 0 0 0 2];
    
    n = numel(h1)-2;
    J = [zeros(n) eye(n) ; -eye(n) zeros(n)];
    
    genA{1} = J*H1;
    genA{2} = J*H2;
    genA{3} = J*H3;
    
    [V,D] = eig(genA{1});
    
elseif n == 9                       % Provides an example of a diagable but non-imaginary drift generator that gives B=C. The set generates sp(4).
    h1 = [2 -2 -7 -3];
    H1 = diag(h1);
    H2 = [1 2 0 0; 2 1 0 0; 0 0 1 0; 0 0 0 1];
    H3 = [2 3 4 0; 3 2 0 0; 4 0 2 0; 0 0 0 2];
    
    k = 2;
    J = [zeros(k) eye(k) ; -eye(k) zeros(k)];
    
    genA{1} = J*H1;
    genA{2} = J*H2;   
    genA{3} = J*H3;
    
    [V,D] = eig(genA{1});
    
elseif n == 10                      % Random 6 by 6s.
    H1 = [1 2 0 5 0 1; 2 3 0 1 0 0; 0 0 4 2 0 0; 5 1 2 1 0 0; 0 0 0 0 1 0; 1 0 0 0 0 1];
    H2 = [1 2 3 4 5 6; 2 2 0 1 0 0; 3 0 1 0 1 0; 4 1 0 2 0 1; 5 0 1 0 2 0; 6 0 0 1 0 2];
    H3 = [1 2 2 2 2 2; 2 1 0 0 0 0; 2 0 1 0 0 0; 2 0 0 1 0 0; 2 0 0 0 1 0; 2 0 0 0 0 3];
  
    k = 3;
    J = [zeros(k) eye(k) ; -eye(k) zeros(k)];
    
    genA{1} = J*H1;
    genA{2} = J*H2;   
    genA{3} = J*H3;
    
    [V,D] = eig(genA{1});
    
elseif n == 11                      % Wu matrices in their symplectic state, via Marco isomorphism. These are symplectic generators, not Hamiltonians.
    genA{1} = [0 -0.5; 0.5 0];
    genA{2} = [0 0.5; 0.5 0];
    genA{3} = [-0.5 0; 0 0.5];
    
    [V,D] = eig(genA{1});
    
elseif n == 12                      % Elliott example of sl(4,R) generating set.
    genA{1} = [0 1 0 -2; 1 0 1 0; 0 1 0 1; -2 0 1 0];
    genA{2} = [1 0 0 0; 0 4 0 0; 0 0 -2 0; 0 0 0 -3];
    
    V = 0; D = 0;
    
end